### ISSUE TITLE
Intro Jupyter Notebook does not work due to missing definition in planar.py

### ISSUE THREAD

**Issue by plainerman** [bgroenks96/normalizing-flows#2]
When running the intro notebook file, I get the following error

```
...
~\normalizing-flows\normalizing_flows\flows\affine\planar.py in _forward(self, z, args)
     47         # compute log det jacobian
     48         dh_dz = tf.multiply(self.dh(wzb), w) # (batch_size, 1, d)
---> 49         r = 1.0 if self.use_residual else 0.0
     50         ldj = tf.math.log(tf.math.abs(r + tf.matmul(dh_dz, u_hat)))
     51         return tf.squeeze(z_, axis=-1), ldj

AttributeError: 'Planar' object has no attribute 'use_residual'
```

I could resolve this error by adding to the init function in https://github.com/bgroenks96/normalizing-flows/blob/e485fe0875c117517353a9ab40e19ff951561cfc/normalizing_flows/flows/affine/planar.py#L11

```
self.use_residual = True
```

I am not quite sure what the appropriate way to resolve this issue is and whether your notebook has been run with residual or without.

Should we set a default value in the init function? Or should the intro notebook be extended and include a value for this field? Or should we add a parameter?

And thanks for the great repository.

**Comment by bgroenks96** [comment]
Sorry, I must have missed the notification for this. That shouldn't happen, I'll take a look.

**Comment by bgroenks96** [comment]
I don't think that was ever intended to be there. I vaguely recall wanting to experiment with planar flows without the residual (this makes it invertible), but this never got implemented. The default (correct) behavior is to include the residual. This has been corrected. Thanks for bringing up the issue!

**Comment by plainerman** [comment]
Thank you very much for resolving it so quickly! :)
